use ETRADE4

/*
select*from USERS

select*from ADDRESS


select*from TOWNS

*/


select
	U.USERNAME_ AS Kulanici,U.NAMESURNAME AS adsoyad,
	CT.CITY IL,T.TOWN AS ÝLCE,D.DISTRICT AS SEMT,A.ADDRESSTEXT AS ACIKADRRES,
	O.ID AS SIPARISID,O.DATE_ AS TARÝH,O.TOTALPRICE as tutar,
	P.DATE_ as odemetarih,P.APPROVECODE AS bankakodu,
	I.DATE_ AS FATURATARIHI ,I.CARGOFICHENO AS FÝS,
	IT.ITEMCODE AS URUNKODU,IT.ITEMNAME AS URUNAD,OD.AMOUNT AS MÝKTAR,OD.UNITPRICE AS BÝRÝMFÝYAT,
	OD.LINETOTAL AS SATIRTOPLAMI

	
		
from Orders O 
	INNER JOIN USERS U ON U.ID=O.USERID
	INNER JOIN ADDRESS A ON A.ID=O.USERID
	INNER JOIN CITIES  CT ON CT.ID=A.USERID
	INNER JOIN TOWNS T ON T.ID=A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I on I.ORDERID=O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	INNER JOIN ITEMS IT ON IT.ID=OD.ITEMID
WHERE 

U.NAMESURNAME='Talha CANIKARA'

