--concat 



select CONCAT('ayhan',' ','çelik')
select CONCAT_WS(' ', 'AYHAN','ÇELÝK')

USE ETRADE4

SELECT 
USERNAME_+''+PASSWORD_+' '+NAMESURNAME,
CONCAT(USERNAME_,'',PASSWORD_,' ',NAMESURNAME),
CONCAT_WS(USERNAME_,'',PASSWORD_,' ',NAMESURNAME),
*FROM  USERS