--FORMAT


--SELECT FORMAT(GETDATE(),'D','en-us')


--LEFT RÝGHT LEN

SELECT LEFT('AYHAN ÇELÝK',4)
SELECT RIGHT('AYHAN ÇELÝK',4)
SELECT LEN('1234567890')


SELECT LEFT('AYHAN ÇELÝK',5)
SELECT RIGHT('AYHAN ÇELÝK',9)
SELECT LEFT('AYHAN ÇELÝK',CHARINDEX(' ','AYHAN ÇELÝK'))



SELECT RIGHT('AYHAN ÇELÝK',LEN('AYHAN ÇELÝK')-CHARINDEX(' ','AYHAN ÇELÝK'))


USE ETRADE4


SELECT

LEFT(NAMESURNAME,CHARINDEX(' ',NAMESURNAME)),RIGHT(NAMESURNAME,LEN(NAMESURNAME)-CHARINDEX(' ',NAMESURNAME)) 

FROM USERS



