USE ETRADE4
--TARÝHE GÖRE SÝPARÝÞ DAÐILIMI


/*
select 

convert(DATE,O.DATE_) TARÝH,
sum(OD.LINETOTAL)AS TOPLAMSÝPARÝS_TUTAR,
SUM(OD.AMOUNT)AS TOPLAMSÝPARÝS_MÝKTAR,
SUM(OD.ID) AS TOPLAMSÝPARÝS
from ORDERS as O
	inner join USERS U on O.USERID= U.ID
	inner join ADDRESS A ON A.ID= O.ADDRESSID
	inner join CITIES CT ON CT.ID = A.CITYID
	inner join TOWNS T ON T.ID = A.TOWNID
	inner join DISTRICTS D on D.ID = A.DISTRICTID
	inner join PAYMENTS P ON P.ORDERID = O.ID 
	inner join INVOICES I ON I.ORDERID = O.ID
	inner join ORDERDETAILS OD ON OD.ORDERID = O.ID
	inner join ITEMS ITM on ITM.ID = OD.ITEMID
GROUP BY convert(DATE,O.DATE_)
ORDER BY convert(DATE,O.DATE_)
*/
--AYLARA GÖRE


USE ETRADE4
--TARÝHE GÖRE SÝPARÝÞ DAÐILIMI



select 
DATEPART (YEAR,O.DATE_) YIL,
DATEPART (MONTH,O.DATE_) AY,
CASE



	WHEN DATEPART (MONTH,O.DATE_)=1 THEN 'ocak'
	WHEN DATEPART (MONTH,O.DATE_)=2 THEN 'subat'
	WHEN DATEPART (MONTH,O.DATE_)=3 THEN 'mart'
	WHEN DATEPART (MONTH,O.DATE_)=4 THEN 'nisan'
	WHEN DATEPART (MONTH,O.DATE_)=5 THEN 'mayis'
	WHEN DATEPART (MONTH,O.DATE_)=6 THEN 'haziran'
	WHEN DATEPART (MONTH,O.DATE_)=7 THEN 'temmuz'
	WHEN DATEPART (MONTH,O.DATE_)=8 THEN 'agustos'
	WHEN DATEPART (MONTH,O.DATE_)=9 THEN 'eylül'
	WHEN DATEPART (MONTH,O.DATE_)=10 THEN 'ekim'
	WHEN DATEPART (MONTH,O.DATE_)=11 THEN 'kasým'
	WHEN DATEPART (MONTH,O.DATE_)=12 THEN 'aralýk'
end as ayadi,

sum(OD.LINETOTAL)AS TOPLAMSÝPARÝS_TUTAR,
SUM(OD.AMOUNT)AS TOPLAMSÝPARÝS_MÝKTAR,
SUM(OD.ID) AS TOPLAMSÝPARÝS
from ORDERS as O
	inner join USERS U on O.USERID= U.ID
	inner join ADDRESS A ON A.ID= O.ADDRESSID
	inner join CITIES CT ON CT.ID = A.CITYID
	inner join TOWNS T ON T.ID = A.TOWNID
	inner join DISTRICTS D on D.ID = A.DISTRICTID
	inner join PAYMENTS P ON P.ORDERID = O.ID 
	inner join INVOICES I ON I.ORDERID = O.ID
	inner join ORDERDETAILS OD ON OD.ORDERID = O.ID
	inner join ITEMS ITM on ITM.ID = OD.ITEMID
GROUP BY DATEPART (YEAR,O.DATE_),DATEPART (MONTH,O.DATE_)
ORDER BY DATEPART (YEAR,O.DATE_),DATEPART (MONTH,O.DATE_)

