USE ETRADE4

--- ORTALAMA TESLÝMAT SÜRESÝ


SELECT
/*
O.ID AS SIPARÝSID,
O.DATE_ AS SÝPARÝSTARÝHÝ_,

I.DATE_ AS FATURATARÝHÝ_,

DATEDIFF(HOUR,O.DATE_,I.DATE_)AS TESLÝMATSURESÝ_SAAT
*/
MIN (DATEDIFF(HOUR,O.DATE_,I.DATE_))AS ENKÝSASURESÝ_SAAT,
MAX  (DATEDIFF(HOUR,O.DATE_,I.DATE_))AS ENUZUNNSURESÝ_SAAT,
 AVG  (DATEDIFF(HOUR,O.DATE_,I.DATE_))AS ORTALAMATESLÝMATSURESÝ_SAAT

from ORDERS as O
	inner join USERS U on O.USERID= U.ID
	inner join ADDRESS A ON A.ID= O.ADDRESSID
	inner join CITIES CT ON CT.ID = A.CITYID
	inner join TOWNS T ON T.ID = A.TOWNID
	inner join DISTRICTS D on D.ID = A.DISTRICTID
	inner join PAYMENTS P ON P.ORDERID = O.ID 
	inner join INVOICES I ON I.ORDERID = O.ID
	/*inner join ORDERDETAILS OD ON OD.ORDERID = O.ID
	inner join ITEMS ITM on ITM.ID = OD.ITEMID*/
	
