USE ETRADE4

--ödemelere göre  DAÐILIMI

--select DISTINCT  PAYMENTTYPE from PAYMENTS
select
  datepart(MONTH,DATE_)AS AY,
  datepart(YEAR,DATE_)AS YIL,
CASE 
	WHEN PAYMENTTYPE=1 THEN 'KREDÝ KARTI'
	WHEN PAYMENTTYPE=2 THEN 'BANKA HAVALESÝ'
END AS ODEMETURU_aciklama,
  SUM(PAYMENTTOTAL) AS TOPLAMTUTAR
  from PAYMENTS
  GROUP BY PAYMENTTYPE,datepart(MONTH,DATE_), datepart(YEAR,DATE_)
  ORDER BY datepart(MONTH,DATE_),PAYMENTTYPE, datepart(YEAR,DATE_)
