USE ETRADE
Select 
ID,CITY
[ID], [CUSTOMERNAME], [CITY], [BIRTHDATE], [DISTRICT], [GENDER]
from Customer

INSERT INTO Customer
(CUSTOMERNAME,CITY,BIRTHDATE,DISTRICT,GENDER)
VALUES 
('MEHMET ÖZAL','Antalya','1990-12-21','Alanya','E')

INSERT INTO Customer
(CUSTOMERNAME,CITY,BIRTHDATE,DISTRICT,GENDER)
VALUES 
('volkan ÖZAL','Ordu','1984-01-21','Fatsa','E')

INSERT INTO Customer
(CUSTOMERNAME,CITY,BIRTHDATE,DISTRICT,GENDER)
VALUES 
('ayþe kara','Ýstanbul','1999-06-01','Kadýköy','K')


